export { default as Loader } from '../..\\components\\Loader.vue'
export { default as ShapeWithAnimation } from '../..\\components\\ShapeWithAnimation.vue'
export { default as AboutGallery } from '../..\\components\\about\\AboutGallery.vue'
export { default as AboutPageHeader } from '../..\\components\\about\\AboutPageHeader.vue'
export { default as AboutPageHeaderThree } from '../..\\components\\about\\AboutPageHeaderThree.vue'
export { default as AboutPageHeaderTwo } from '../..\\components\\about\\AboutPageHeaderTwo.vue'
export { default as AboutFunFactTwo } from '../..\\components\\about\\FunFactTwo.vue'
export { default as AboutSpecialPolicy } from '../..\\components\\about\\SpecialPolicy.vue'
export { default as AboutTeamMember } from '../..\\components\\about\\TeamMember.vue'
export { default as AboutVideoCallToAction } from '../..\\components\\about\\VideoCallToAction.vue'
export { default as BannerStyleFour } from '../..\\components\\banner\\BannerStyleFour.vue'
export { default as BannerStyleOne } from '../..\\components\\banner\\BannerStyleOne.vue'
export { default as BannerStyleThree } from '../..\\components\\banner\\BannerStyleThree.vue'
export { default as BannerStyleTwo } from '../..\\components\\banner\\BannerStyleTwo.vue'
export { default as BecomeInstructorCTA } from '../..\\components\\become-instructor\\BecomeInstructorCTA.vue'
export { default as BecomeInstructorPageHeader } from '../..\\components\\become-instructor\\BecomeInstructorPageHeader.vue'
export { default as BecomeInstructorDiscoverPotential } from '../..\\components\\become-instructor\\DiscoverPotential.vue'
export { default as BecomeInstructorFunFact } from '../..\\components\\become-instructor\\FunFact.vue'
export { default as BecomeInstructorBanner } from '../..\\components\\become-instructor\\InstructorBanner.vue'
export { default as BecomeInstructorTab } from '../..\\components\\become-instructor\\InstructorTab.vue'
export { default as BlogArticleGridStyle } from '../..\\components\\blog\\BlogArticleGridStyle.vue'
export { default as BlogArticleGridStyleTwo } from '../..\\components\\blog\\BlogArticleGridStyleTwo.vue'
export { default as BlogArticleListStyle } from '../..\\components\\blog\\BlogArticleListStyle.vue'
export { default as BlogSectionOne } from '../..\\components\\blog\\BlogSectionOne.vue'
export { default as BlogSectionThree } from '../..\\components\\blog\\BlogSectionThree.vue'
export { default as BlogSectionTwo } from '../..\\components\\blog\\BlogSectionTwo.vue'
export { default as BlogSidebar } from '../..\\components\\blog\\BlogSidebar.vue'
export { default as BlogComment } from '../..\\components\\blog\\Comment.vue'
export { default as BlogLatestPost } from '../..\\components\\blog\\LatestPost.vue'
export { default as BlogSocialShareButtonGroup } from '../..\\components\\blog\\SocialShareButtonGroup.vue'
export { default as BrandPartner } from '../..\\components\\brand-partner\\BrandPartner.vue'
export { default as BrandPartnerCarousel } from '../..\\components\\brand-partner\\BrandPartnerCarousel.vue'
export { default as BrandPartnerThree } from '../..\\components\\brand-partner\\BrandPartnerThree.vue'
export { default as BrandPartnerTwo } from '../..\\components\\brand-partner\\BrandPartnerTwo.vue'
export { default as ContactFormOne } from '../..\\components\\contact\\ContactFormOne.vue'
export { default as ContactInfoStyleOne } from '../..\\components\\contact\\ContactInfoStyleOne.vue'
export { default as ContactInfoStyleTwo } from '../..\\components\\contact\\ContactInfoStyleTwo.vue'
export { default as ContactGoogleMap } from '../..\\components\\contact\\GoogleMap.vue'
export { default as CategoriesBrowseSubject } from '../..\\components\\categories\\BrowseSubject.vue'
export { default as CategoriesCategoryItemStyleOne } from '../..\\components\\categories\\CategoryItemStyleOne.vue'
export { default as CategoriesCategoryItemStyleThree } from '../..\\components\\categories\\CategoryItemStyleThree.vue'
export { default as CategoriesCategoryItemStyleTwo } from '../..\\components\\categories\\CategoryItemStyleTwo.vue'
export { default as CategoriesTopCategoriesWrapperOne } from '../..\\components\\categories\\TopCategoriesWrapperOne.vue'
export { default as CategoriesTopCategoriesWrapperThree } from '../..\\components\\categories\\TopCategoriesWrapperThree.vue'
export { default as CategoriesTopCategoriesWrapperTwo } from '../..\\components\\categories\\TopCategoriesWrapperTwo.vue'
export { default as ElementsBreadcrumbStyleOne } from '../..\\components\\elements\\BreadcrumbStyleOne.vue'
export { default as ElementsBreadcrumbStyleTwo } from '../..\\components\\elements\\BreadcrumbStyleTwo.vue'
export { default as ElementsButtonDefault } from '../..\\components\\elements\\ButtonDefault.vue'
export { default as ElementsButtonStyleOne } from '../..\\components\\elements\\ButtonStyleOne.vue'
export { default as ElementsCallToActionOne } from '../..\\components\\elements\\CallToActionOne.vue'
export { default as ElementsCategoryFilterButton } from '../..\\components\\elements\\CategoryFilterButton.vue'
export { default as ElementsCountdown } from '../..\\components\\elements\\Countdown.vue'
export { default as ElementsCountdownSignupSection } from '../..\\components\\elements\\CountdownSignupSection.vue'
export { default as ElementsFunFactStyleTwo } from '../..\\components\\elements\\FunFactStyleTwo.vue'
export { default as ElementsFunFactThree } from '../..\\components\\elements\\FunFactThree.vue'
export { default as ElementsHeaderSearchBox } from '../..\\components\\elements\\HeaderSearchBox.vue'
export { default as ElementsIconBoxOne } from '../..\\components\\elements\\IconBoxOne.vue'
export { default as ElementsModal } from '../..\\components\\elements\\Modal.vue'
export { default as ElementsModalCopy } from '../..\\components\\elements\\ModalCopy.vue'
export { default as ElementsOurSpeakers } from '../..\\components\\elements\\OurSpeakers.vue'
export { default as ElementsPricingPlanStyleOne } from '../..\\components\\elements\\PricingPlanStyleOne.vue'
export { default as ElementsPricingPlanStyleTwo } from '../..\\components\\elements\\PricingPlanStyleTwo.vue'
export { default as ElementsSectionTitleStyleOne } from '../..\\components\\elements\\SectionTitleStyleOne.vue'
export { default as ElementsStarRating } from '../..\\components\\elements\\StarRating.vue'
export { default as EventsEventArticle } from '../..\\components\\events\\EventArticle.vue'
export { default as EventsEventArticleStyleTwo } from '../..\\components\\events\\EventArticleStyleTwo.vue'
export { default as EventsEventArticleThree } from '../..\\components\\events\\EventArticleThree.vue'
export { default as EventsEventFilterWidget } from '../..\\components\\events\\EventFilterWidget.vue'
export { default as EventsEventListArticle } from '../..\\components\\events\\EventListArticle.vue'
export { default as EventsEventSidebar } from '../..\\components\\events\\EventSidebar.vue'
export { default as EventsOne } from '../..\\components\\events\\EventsOne.vue'
export { default as EventsThree } from '../..\\components\\events\\EventsThree.vue'
export { default as EventsTwo } from '../..\\components\\events\\EventsTwo.vue'
export { default as EventsPopularEvent } from '../..\\components\\events\\PopularEvent.vue'
export { default as FaqsFaqListWrapper } from '../..\\components\\faqs\\FaqListWrapper.vue'
export { default as FaqsFaqPageHeader } from '../..\\components\\faqs\\FaqPageHeader.vue'
export { default as FaqsSearchTopic } from '../..\\components\\faqs\\SearchTopic.vue'
export { default as CoursesCourseCurriculum } from '../..\\components\\courses\\CourseCurriculum.vue'
export { default as CoursesCourseDetailsBreadcrumb } from '../..\\components\\courses\\CourseDetailsBreadcrumb.vue'
export { default as CoursesCourseDetailsContent } from '../..\\components\\courses\\CourseDetailsContent.vue'
export { default as CoursesCourseDetailsHeader } from '../..\\components\\courses\\CourseDetailsHeader.vue'
export { default as CoursesCourseFilter } from '../..\\components\\courses\\CourseFilter.vue'
export { default as CoursesCourseGridStyle } from '../..\\components\\courses\\CourseGridStyle.vue'
export { default as CoursesCourseGridStyleThree } from '../..\\components\\courses\\CourseGridStyleThree.vue'
export { default as CoursesCourseGridStyleTwo } from '../..\\components\\courses\\CourseGridStyleTwo.vue'
export { default as CoursesCourseListStyle } from '../..\\components\\courses\\CourseListStyle.vue'
export { default as CoursesByCategories } from '../..\\components\\courses\\CoursesByCategories.vue'
export { default as CoursesByCategoriesBackup } from '../..\\components\\courses\\CoursesByCategoriesBackup.vue'
export { default as CoursesSectionOne } from '../..\\components\\courses\\CoursesSectionOne.vue'
export { default as CoursesSectionThree } from '../..\\components\\courses\\CoursesSectionThree.vue'
export { default as CoursesSectionTwo } from '../..\\components\\courses\\CoursesSectionTwo.vue'
export { default as CoursesLanguageCourses } from '../..\\components\\courses\\LanguageCourses.vue'
export { default as CoursesTrendingCourses } from '../..\\components\\courses\\TrendingCourses.vue'
export { default as FeatureListStyleOne } from '../..\\components\\feature\\FeatureListStyleOne.vue'
export { default as FeatureGuides } from '../..\\components\\feature\\Guides.vue'
export { default as FooterCopyright } from '../..\\components\\footer\\FooterCopyright.vue'
export { default as FooterStyleFour } from '../..\\components\\footer\\FooterStyleFour.vue'
export { default as FooterStyleOne } from '../..\\components\\footer\\FooterStyleOne.vue'
export { default as FooterStyleThree } from '../..\\components\\footer\\FooterStyleThree.vue'
export { default as FooterStyleTwo } from '../..\\components\\footer\\FooterStyleTwo.vue'
export { default as HeaderDefault } from '../..\\components\\header\\HeaderDefault.vue'
export { default as HeaderEducationCenter } from '../..\\components\\header\\HeaderEducationCenter.vue'
export { default as HeaderLanguageAcademic } from '../..\\components\\header\\HeaderLanguageAcademic.vue'
export { default as HeaderMain } from '../..\\components\\header\\HeaderMain.vue'
export { default as HeaderSimple } from '../..\\components\\header\\HeaderSimple.vue'
export { default as HeaderTop } from '../..\\components\\header\\HeaderTop.vue'
export { default as HeaderTopLightBg } from '../..\\components\\header\\HeaderTopLightBg.vue'
export { default as HeaderTopNotificationBar } from '../..\\components\\header\\HeaderTopNotificationBar.vue'
export { default as HeaderTopStyleTwo } from '../..\\components\\header\\HeaderTopStyleTwo.vue'
export { default as HeaderTopUniversity } from '../..\\components\\header\\HeaderTopUniversity.vue'
export { default as HeaderNavigation } from '../..\\components\\header\\Navigation.vue'
export { default as HeaderNavigationMain } from '../..\\components\\header\\NavigationMain.vue'
export { default as HeaderOffCanvasMobileMenu } from '../..\\components\\header\\OffCanvasMobileMenu.vue'
export { default as HeaderOffcanvasSearchBox } from '../..\\components\\header\\OffcanvasSearchBox.vue'
export { default as HeaderResponsiveMobileMenu } from '../..\\components\\header\\ResponsiveMobileMenu.vue'
export { default as HeaderUniversityNavigationBar } from '../..\\components\\header\\UniversityNavigationBar.vue'
export { default as HeroBannerOne } from '../..\\components\\hero\\HeroBannerOne.vue'
export { default as HeroCourseHub } from '../..\\components\\hero\\HeroCourseHub.vue'
export { default as HeroEducationCenter } from '../..\\components\\hero\\HeroEducationCenter.vue'
export { default as HeroLanguageAcademic } from '../..\\components\\hero\\HeroLanguageAcademic.vue'
export { default as HeroOnlineAcademy } from '../..\\components\\hero\\HeroOnlineAcademy.vue'
export { default as HeroUniversity } from '../..\\components\\hero\\HeroUniversity.vue'
export { default as InstructorDashboardVerticalMenu } from '../..\\components\\instructor\\DashboardVerticalMenu.vue'
export { default as Instructor } from '../..\\components\\instructor\\Instructor.vue'
export { default as InstructorDashboardHeader } from '../..\\components\\instructor\\InstructorDashboardHeader.vue'
export { default as InstructorInfoStyleOne } from '../..\\components\\instructor\\InstructorInfoStyleOne.vue'
export { default as InstructorReviews } from '../..\\components\\instructor\\InstructorReviews.vue'
export { default as InstructorTwo } from '../..\\components\\instructor\\InstructorTwo.vue'
export { default as InstructorMobileNavigation } from '../..\\components\\instructor\\MobileNavigation.vue'
export { default as InstructorOffCanvasMobileMenu } from '../..\\components\\instructor\\OffCanvasMobileMenu.vue'
export { default as Login } from '../..\\components\\login\\Login.vue'
export { default as NewsletterOne } from '../..\\components\\newsletter\\NewsletterOne.vue'
export { default as Register } from '../..\\components\\register\\Register.vue'
export { default as SectionCoursesSectionOneBackup } from '../..\\components\\section\\CoursesSectionOneBackup.vue'
export { default as TabsDemo } from '../..\\components\\tabs\\Demo.vue'
export { default as TabsTab } from '../..\\components\\tabs\\Tab.vue'
export { default as Tabs } from '../..\\components\\tabs\\Tabs.vue'
export { default as TestimonialFour } from '../..\\components\\testimonial\\TestimonialFour.vue'
export { default as TestimonialItem } from '../..\\components\\testimonial\\TestimonialItem.vue'
export { default as TestimonialItemStyleTwo } from '../..\\components\\testimonial\\TestimonialItemStyleTwo.vue'
export { default as TestimonialOne } from '../..\\components\\testimonial\\TestimonialOne.vue'
export { default as TestimonialStyleTwo } from '../..\\components\\testimonial\\TestimonialStyleTwo.vue'
export { default as TestimonialThree } from '../..\\components\\testimonial\\TestimonialThree.vue'
export { default as UniversityAcademics } from '../..\\components\\university\\Academics.vue'
export { default as UniversityApplyCallToAction } from '../..\\components\\university\\ApplyCallToAction.vue'
export { default as UniversityCampusLife } from '../..\\components\\university\\CampusLife.vue'
export { default as ElementsTab } from '../..\\components\\elements\\tab\\Tab.vue'
export { default as ElementsTabTabs } from '../..\\components\\elements\\tab\\Tabs.vue'
export { default as ZoomArticle } from '../..\\components\\zoom-meetings\\ZoomArticle.vue'
export { default as CoursesSidebarCategoryWidget } from '../..\\components\\courses\\sidebar\\CategoryWidget.vue'
export { default as CoursesSidebarCourseSidebar } from '../..\\components\\courses\\sidebar\\CourseSidebar.vue'
export { default as CoursesSidebarInstructorWidget } from '../..\\components\\courses\\sidebar\\InstructorWidget.vue'
export { default as CoursesSidebarLanguagesWidget } from '../..\\components\\courses\\sidebar\\LanguagesWidget.vue'
export { default as CoursesSidebarLevelWidget } from '../..\\components\\courses\\sidebar\\LevelWidget.vue'
export { default as CoursesSidebarPricingWidget } from '../..\\components\\courses\\sidebar\\PricingWidget.vue'
export { default as CoursesSidebarRelatedCourse } from '../..\\components\\courses\\sidebar\\RelatedCourse.vue'

// nuxt/nuxt.js#8607
function wrapFunctional(options) {
  if (!options || !options.functional) {
    return options
  }

  const propKeys = Array.isArray(options.props) ? options.props : Object.keys(options.props || {})

  return {
    render(h) {
      const attrs = {}
      const props = {}

      for (const key in this.$attrs) {
        if (propKeys.includes(key)) {
          props[key] = this.$attrs[key]
        } else {
          attrs[key] = this.$attrs[key]
        }
      }

      return h(options, {
        on: this.$listeners,
        attrs,
        props,
        scopedSlots: this.$scopedSlots,
      }, this.$slots.default)
    }
  }
}
